/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    Error: typeof import('./src/views/home/components/empty/index.vue')['default']
    Footer: typeof import('./src/views/home/components/wall-footer/index.vue')['default']
    Header: typeof import('./src/views/home/components/wall-header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YqButton: typeof import('./src/components/yq-button/index.vue')['default']
    YqDrawer: typeof import('./src/components/yq-drawer/index.vue')['default']
    YqImgView: typeof import('./src/views/home/components/yq-img-view/index.vue')['default']
    YqLoading: typeof import('./src/components/yq-loading/index.vue')['default']
  }
}
