/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YqButton: typeof import('./src/components/yq-button/index.vue')['default']
    YqImgView: typeof import('./src/components/yq-img-view/index.vue')['default']
    YqMessage: typeof import('./src/components/yq-message/index.vue')['default']
    YqModal: typeof import('./src/components/yq-modal/index.vue')['default']
  }
}
